### ISSUE TITLE
Contact box does not work.

### ISSUE THREAD

**Issue by jgkamat** [y7kim/agency-jekyll-theme#4]
The contact box gives an error message of 'Sorry , it seems that my mail server is not responding. Please try again later!' regardless of what is put in it! 
This is true for the default email specified in the live demo as well!

**Comment by desaiuditd** [comment]
You will need a PHP Web Server for the mail to be delivered successfully. Since the functionality of sending the mail is written in PHP.

Ref : [check here](https://github.com/y7kim/agency-jekyll-theme/blob/gh-pages/mail/contact_me.php)

Though you can customize that according to your need and availability of server. Or you can use any third party form setup & mail delivery service like [Simple Form](http://getsimpleform.com/)

**Comment by jgkamat** [comment]
So this will only work if you are hosting from a machine you can control (not github pages)?

If not, i'll probably just use simpleform.

**Comment by desaiuditd** [comment]
Yup. I myself use Simple Form. :wink:

**Comment by jgkamat** [comment]
Thanks so much! 
I really appreciate the work you put into this theme =D
